#include <chrono>
#include <thread>
#include <unistd.h>
#include "Vec_Tools.hpp"
#include "Math_Tools.hpp"
#include "Sys_Tools.hpp"
#include "Vector_3.hpp"
#include "Tensor4_3D.hpp"
#include "SymmTensor4_3D.hpp"
#include "IEN_FEM.hpp"
#include "NodalBC.hpp"
#include "NodalBC_3D_inflow.hpp"
#include "ElemBC_3D.hpp"
#include "ElemBC_3D_outflow.hpp"

int main(int argc, char *argv[])
{
  // this is generated in Matlab
  const Tensor2_3D ten( 0.768873553, -0.2731582749, -0.539163073,
                        1.439856977, -3.611316877,  -0.396276585,
                        0.245231427, 1.74886152,  0.1902972708 );


  const Tensor2_3D exp_ten = Ten2::exp( ten );

  // this was generated by 'expm' function in Matlab
  const Tensor2_3D exp_ten_matlab( 1.737863590027021,  -0.364881931951244,  -0.742251904755426,
     0.532145617021775,  -0.116101731167550,  -0.303982143105766,
    1.042432871801321,   0.382573338479823,   0.827177565318633 ); 

  ten.print();
  std::cout<<"expm(X) = \n";
  exp_ten_matlab.print();
  std::cout<<"\nexp(X) = \n";
  exp_ten.print();
  if( exp_ten.is_identical(exp_ten_matlab, 1.0e-15) ) std::cout<<"\nThe differnece is less than 1.0e-15!"<<std::endl;
  else std::cout<<"\nERROR: the difference is larger than 1.0e-15!"<<std::endl;
  
  Tensor2_3D diff = exp_ten - exp_ten_matlab;
  diff.print();
  return EXIT_SUCCESS;
}

// EOF
