# This File Setup the value of EXTRA_LINK_LIBS and the INCLUDE_DIRS

MESSAGE(STATUS "=================== External library setup ===================")

# ===============================================
# SET VTK
# ===============================================
SET(VTK_INCLUDE_DIRS ${VTK_INCLUDE_DIRS}
  ${VTK_DIR}/include/${VTK_VERSION})

IF(${VTK_VERSION} MATCHES "vtk-5.10")
  SET(VTK_LINK_DIRS ${VTK_LINK_DIRS} ${VTK_DIR}/lib/${VTK_VERSION})
ELSE(${VTK_VERSION} MATCHES "vtk-5.10")
  SET(VTK_LINK_DIRS ${VTK_LINK_DIRS} ${VTK_DIR}/lib)
ENDIF(${VTK_VERSION} MATCHES "vtk-5.10")

SET(EXTRA_LINK_LIBS ${EXTRA_LINK_LIBS} ${VTK_link_lib} )

# ===============================================
# SET HDF5 library
# ===============================================
IF(DEFINED HDF5_DIR)
  MESSAGE(STATUS "HDF5 DIR = ${HDF5_DIR}")
ELSE(DEFINED HDF5_DIR)
  MESSAGE(FATAL_ERROR "HDF5_DIR is NOT defined! check ~/PETSc_VTK.cmake")
ENDIF(DEFINED HDF5_DIR)

SET(HDF5_LIBRARY_DIRS ${HDF5_DIR}/lib)
SET(HDF5_INCLUDE_DIRS ${HDF5_DIR}/include)
SET(HDF5_LINK_LIBS hdf5)

SET(EXTRA_LINK_LIBS ${EXTRA_LINK_LIBS} ${HDF5_LINK_LIBS})

# INCLUDE LIBRARY HEADER FILES
INCLUDE_DIRECTORIES( ${VTK_INCLUDE_DIRS} )
#INCLUDE_DIRECTORIES( ${METIS_INCLUDE_DIRS} )
INCLUDE_DIRECTORIES( ${HDF5_INCLUDE_DIRS} )

# LINK TO LIBRARY LIBS
LINK_DIRECTORIES(${VTK_LINK_DIRS})
LINK_DIRECTORIES(${HDF5_LIBRARY_DIRS})

# EOF
