# Load appropriate system files into the configuration file

if( $ENV{MACHINE_NAME} MATCHES "poincare")
  message(STATUS "JL's Mac laptop banach")
  include(${CMAKE_CURRENT_LIST_DIR}/poincare.cmake)
elseif( $ENV{MACHINE_NAME} MATCHES "kolmogorov")
  message(STATUS "Mac laptop Kolmogorov")
  include(${CMAKE_CURRENT_LIST_DIR}/kolmogorov.cmake)
elseif( $ENV{MACHINE_NAME} MATCHES "ladyzhenskaya")
  message(STATUS "Linux desktop Ladyzhenskaya")
  include(${CMAKE_CURRENT_LIST_DIR}/ladyzhenskaya.cmake)
elseif( $ENV{MACHINE_NAME} MATCHES "sp2")
  message(STATUS "TACC Stampede2")
  include(${CMAKE_CURRENT_LIST_DIR}/stampede2_juliu.cmake)
elseif( $ENV{MACHINE_NAME} MATCHES "LS5")
  message(STATUS "TACC Lonestar5")
  include(${CMAKE_CURRENT_LIST_DIR}/ls5.cmake)
elseif( $ENV{MACHINE_NAME} MATCHES "comet")
  message(STATUS "SDSC Comet")
  include(${CMAKE_CURRENT_LIST_DIR}/comet_juliu.cmake)
elseif( $ENV{MACHINE_NAME} MATCHES "sherlock")
  message(STATUS "Stanford Sherlock")
  include(${CMAKE_CURRENT_LIST_DIR}/stanford_sherlock.cmake)
elseif( $ENV{MACHINE_NAME} MATCHES "ingridxlan")
  message(STATUS "Stanford ingridxlan")
  include(${CMAKE_CURRENT_LIST_DIR}/marsden_linux_ingridxlan.cmake)
elseif( $ENV{MACHINE_NAME} MATCHES "card-jaf-ra2")
  message(STATUS "card-jaf-ra2")
  include(${CMAKE_CURRENT_LIST_DIR}/card-jaf-ra2.cmake)
else($ENV{MACHINE_NAME} MATCHES "poincare")
  message(STATUS "The system cannot be identified.")
endif( $ENV{MACHINE_NAME} MATCHES "poincare")

# End of the file
