#!/bin/bash
#SBATCH -J prepost    # Job Name
#SBATCH -o prepost    # Name of the output and error file (%j expands to jobID)
#SBATCH -N 1 -n 1  # Total number of mpi tasks requested
#SBATCH -p skx-dev  # Queue (partition) name  -- normal, development, gpu, etc.
#SBATCH -t 00:02:00  # Run time (hh:mm:ss) - 1.5 hours
#SBATCH -A TG-CTS130034

ibrun $HOME/build_p1/preprocess3d_h5 -cpu_size 1 -in_ncommon 3
ibrun $HOME/build_p1/dssegso3d \
	      -nqp_tet 5 -nqp_tri 4 -init_step 1.0e-5 -fina_time 1.0e-5 \
	      -nl_refreq 1 -nl_rtol 1.0e-6 -nl_atol 1.0e-6 \
	      -ksp_type fgmres -pc_type fieldsplit \
	      -pc_fieldsplit_type schur \
	      -pc_fieldsplit_schur_factorization_type full \
	      -pc_fieldsplit_schur_precondition selfp \
	      -is_usr_schur NO \
	      -ksp_rtol 1.0e-3 \
	      -ksp_atol 1.0e-50 \
	      -ksp_max_it 200 \
	      -ksp_gmres_restart 200 \
	      -fieldsplit_u_ksp_type gmres \
	      -fieldsplit_u_pc_type hypre \
	      -fieldsplit_u_pc_hypre_boomeramg_coarsen_type HMIS \
	      -fieldsplit_u_pc_hypre_boomeramg_interp_type ext+i \
	      -fieldsplit_u_pc_hypre_boomeramg_truncfactor 0.3 \
	      -fieldsplit_u_pc_hypre_boomeramg_strong_threshold 0.5 \
	      -fieldsplit_u_pc_hypre_boomeramg_P_max 5 \
	      -fieldsplit_u_pc_hypre_boomeramg_agg_nl 2 \
	      -fieldsplit_u_ksp_rtol 1.0e-3 \
	      -fieldsplit_u_ksp_max_it 200 \
	      -fieldsplit_u_ksp_gmres_restart 200 \
	      -fieldsplit_p_ksp_type gmres \
	      -fieldsplit_p_pc_type hypre \
	      -fieldsplit_p_pc_hypre_boomeramg_coarsen_type HMIS \
	      -fieldsplit_p_pc_hypre_boomeramg_interp_type ext+i \
	      -fieldsplit_p_pc_hypre_boomeramg_truncfactor 0.3 \
	      -fieldsplit_p_pc_hypre_boomeramg_strong_threshold 0.5 \
	      -fieldsplit_p_pc_hypre_boomeramg_P_max 5 \
	      -fieldsplit_p_pc_hypre_boomeramg_agg_nl 2 \
	      -fieldsplit_p_ksp_rtol 1.0e-3 \
	      -fieldsplit_p_ksp_max_it 200 \
	      -fieldsplit_p_ksp_gmres_restart 200 \
	      -log_view \
	      -fieldsplit_u_ksp_converged_reason \
	      -fieldsplit_p_ksp_converged_reason \
