#!/bin/bash
#SBATCH -J dd_p1_run    # Job Name
#SBATCH -o scale_dd_1    # Name of the output and error file (%j expands to jobID)
#SBATCH -N 1 -n 1  # Total number of mpi tasks requested
#SBATCH -p skx-normal   # Queue (partition) name  -- normal, development, gpu, etc.
#SBATCH -t 11:00:00  # Run time (hh:mm:ss) - 1.5 hours
#SBATCH -A TG-CTS130034

ibrun $HOME/build_p1/dssegso3d \
	      -nqp_tet 5 -nqp_tri 4 -init_step 1.0e-1 -fina_time 1.0e0 \
	      -nl_refreq 1 -nl_rtol 1.0e-6 -nl_atol 1.0e-6 \
	      -ksp_type gmres -pc_type asm \
	      -sub_ksp_type preonly \
	      -sub_pc_type hypre -sub_pc_hypre_type pilut \
	      -ksp_rtol 1.0e-3 \
	      -ksp_max_it 10000 \
              -ksp_gmres_restart 200 \
	      -ksp_norm_type unpreconditioned \
	      -ksp_converged_reason \
	      -log_view \
	      #-sub_pc_type hypre \
	      #-sub_pc_hypre_boomeramg_coarsen_type HMIS \
	      #-sub_pc_hypre_boomeramg_interp_type ext+i \
	      #-sub_pc_hypre_boomeramg_truncfactor 0.3 \
	      #-sub_pc_hypre_boomeramg_strong_threshold 0.5 \
	      #-sub_pc_hypre_boomeramg_P_max 5 \
	      #-sub_pc_hypre_boomeramg_agg_nl 2 \
#-fieldsplit_p_inner_ksp_monitor_true_residual \
